import type { TutorialLesson } from './types';

export const tutorialLessons: TutorialLesson[] = [
  {
    id: 'freezer-box-basics',
    title: 'Freezer Box Basics',
    description: 'Learn the core grid-input workflow: applying data, crossing, clearing, copying, and understanding field-locking behavior.',
    category: 'freezerBox',
    icon: 'Grid3x3',
    estimatedMinutes: 8,
    steps: [
      {
        id: 'fb-1',
        instruction: 'Click the "Add Box" button to create a new storage box.',
        targetId: 'workspace-add-box-btn',
        action: 'click',
        tooltipPosition: 'auto',
      },
      {
        id: 'fb-2',
        instruction: 'Freezer Box is already selected. Click "Continue" to proceed.',
        targetId: 'box-type-continue-btn',
        action: 'click',
        tooltipPosition: 'auto',
      },
      {
        id: 'fb-3',
        instruction: 'Type "Sample Box 1" as the box name.',
        targetId: 'create-box-name-input',
        action: 'type',
        expectedValue: 'Sample Box 1',
        tooltipPosition: 'bottom',
      },
      {
        id: 'fb-4',
        instruction: 'Click "Create" to save the box.',
        targetId: 'create-box-save-btn',
        action: 'click',
        tooltipPosition: 'top',
      },
      {
        id: 'fb-5',
        instruction: 'Click on the box card to open it and see the grid.',
        targetId: 'workspace-box-card-tutorial',
        action: 'click',
        tooltipPosition: 'bottom',
      },
      {
        id: 'fb-6',
        instruction: 'Click cell A1 and drag to A3 to select the first three cells of row A.',
        targetId: 'grid-cell-A1',
        action: 'click',
        tooltipPosition: 'bottom',
      },
      {
        id: 'fb-7',
        instruction: 'Type "HeLa" in the Name field.',
        targetId: 'input-name-field',
        action: 'type',
        expectedValue: 'HeLa',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-8',
        instruction: 'Type "2M" in the Information field (press Enter to add a second line "30% FBS").',
        targetId: 'input-info-field',
        action: 'type',
        expectedValue: '2M',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-9',
        instruction: 'Select "Date" as the date type.',
        targetId: 'input-date-type-date',
        action: 'click',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-10',
        instruction: 'Pick today\'s date in the date picker.',
        targetId: 'input-date-field',
        action: 'type',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-11',
        instruction: 'Click "Apply to Selected Cells" to save the data to A1, A2, and A3.',
        targetId: 'input-save-btn',
        action: 'click',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-12',
        instruction: 'Click cell B1 and drag to B3 to select the second row.',
        targetId: 'grid-cell-B1',
        action: 'click',
        tooltipPosition: 'bottom',
      },
      {
        id: 'fb-13',
        instruction: 'Type "Alexa 488" in the Information field.',
        targetId: 'input-info-field',
        action: 'type',
        expectedValue: 'Alexa 488',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-14',
        instruction: 'Select "Expiration" as the date type.',
        targetId: 'input-date-type-expiration',
        action: 'click',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-15',
        instruction: 'Pick today\'s date as the expiration date.',
        targetId: 'input-date-field',
        action: 'type',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-16',
        instruction: 'Select the Red background color.',
        targetId: 'color-swatch-red',
        action: 'click',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-17',
        instruction: 'Click "Apply to Selected Cells" to save.',
        targetId: 'input-save-btn',
        action: 'click',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-18',
        instruction: 'Click cell C1 and drag to C3 to select the third row.',
        targetId: 'grid-cell-C1',
        action: 'click',
        tooltipPosition: 'bottom',
      },
      {
        id: 'fb-19',
        instruction: 'Type "BSA" in the Information field.',
        targetId: 'input-info-field',
        action: 'type',
        expectedValue: 'BSA',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-20',
        instruction: 'Click "Apply to Selected Cells" to save.',
        targetId: 'input-save-btn',
        action: 'click',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-21',
        instruction: 'Click cell B1 and drag to B3 to re-select the second row.',
        targetId: 'grid-cell-B1',
        action: 'click',
        tooltipPosition: 'bottom',
      },
      {
        id: 'fb-22',
        instruction: 'Click the "Cross" button to mark these cells as crossed out.',
        targetId: 'input-cross-btn',
        action: 'click',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-23',
        instruction: 'With B1-B3 still selected (or re-select them), notice they are crossed.',
        targetId: 'grid-cell-B1',
        action: 'click',
        tooltipPosition: 'bottom',
      },
      {
        id: 'fb-24',
        instruction: 'Click "Apply to Selected Cells" to reapply data and remove the cross.',
        targetId: 'input-save-btn',
        action: 'click',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-25',
        instruction: 'Select all 6 cells B1 through C3 (drag from B1 to C3).',
        targetId: 'grid-cell-B1',
        action: 'click',
        tooltipPosition: 'bottom',
      },
      {
        id: 'fb-26',
        instruction: 'Click "Clear" to delete the selected cells. Only row A remains.',
        targetId: 'input-clear-btn',
        action: 'click',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-27',
        instruction: 'Select cells A3 through A6 (click A3 then Shift+click A6 or drag).',
        targetId: 'grid-cell-A3',
        action: 'click',
        tooltipPosition: 'bottom',
      },
      {
        id: 'fb-28',
        instruction: 'Click "Apply to Selected Cells" to copy A3\'s data into the empty cells A4, A5, A6.',
        targetId: 'input-save-btn',
        action: 'click',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-29',
        instruction: 'Select cells A4, A5, A6.',
        targetId: 'grid-cell-A4',
        action: 'click',
        tooltipPosition: 'bottom',
      },
      {
        id: 'fb-30',
        instruction: 'Edit the Information field: remove "30% FBS" so only "2M" remains.',
        targetId: 'input-info-field',
        action: 'type',
        expectedValue: '2M',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-31',
        instruction: 'Click "Apply to Selected Cells" to save the change.',
        targetId: 'input-save-btn',
        action: 'click',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-32',
        instruction: 'Select all 6 cells A1 through A6. Notice the Information field shows "Mixed" (locked) because values differ.',
        targetId: 'grid-cell-A1',
        action: 'click',
        tooltipPosition: 'bottom',
      },
      {
        id: 'fb-33',
        instruction: 'Edit the Name field to "HeLa GFP+" (the unlocked field).',
        targetId: 'input-name-field',
        action: 'type',
        expectedValue: 'HeLa GFP+',
        tooltipPosition: 'left',
      },
      {
        id: 'fb-34',
        instruction: 'Click "Apply to Selected Cells" -- only the unlocked Name field updates across all cells.',
        targetId: 'input-save-btn',
        action: 'click',
        tooltipPosition: 'left',
      },
    ],
  },
];

export function getLessonById(id: string): TutorialLesson | undefined {
  return tutorialLessons.find((l) => l.id === id);
}

export function getLessonsByCategory(category: string): TutorialLesson[] {
  return tutorialLessons.filter((l) => l.category === category);
}
